language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer dump-autoload --no-dev

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi

script:
  - find src \( -name '*.php' \) -exec php -l {} \;
  - phpunit